name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t sagar592/frontend-app:latest ./frontend
        docker push sagar592/frontend-app:latest

    - name: Deploy to Frontend EC2 Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FRONTEND_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull sagar592/frontend-app:latest
          docker stop frontend-app || true
          docker rm frontend-app || true
          docker run -d -p 80:80 --name frontend-app sagar592/frontend-app:latest

