name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t sagar592/backend-api:latest ./backend

      - name: Push Docker image
        run: docker push sagar592/backend-api:latest

      - name: Deploy to Backend Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.BACKEND_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            docker pull sagar592/backend-api:latest
            docker stop backend-api || true && docker rm backend-api || true
            docker run -d -p 8000:8000 --name backend-api sagar592/backend-api:latest
